## deno run --config tsconfig.json --allow-net --allow-read --allow-env entry-point.ts

# POST /api/add-book HTTP/1.1
# Host: localhost:8083
# Content-Type: application/json

# {
#     "name": "The Diary Of a Young Girl",
#     "author": "Anne Frank"
# }

# POST /api/add-book HTTP/1.1
# Host: localhost:8083
# Content-Type: application/json

# {
#     "name": "Sapiens: A Brief History of Humankind",
#     "author": "Yuval Noah Harari"
# }

# GET /api/get-book/1 HTTP/1.1
# Host: localhost:8083

# GET /api/Yuval Noah Harari/books HTTP/1.1
# Host: localhost:8083

# GET /api/search?id=1&name=The Diary Of a Young Girl HTTP/1.1
# Host: localhost:8083

# GET /api/all-books HTTP/1.1
# Host: localhost:8083